/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica_04;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author terry
 */
public class JFrame extends javax.swing.JFrame {
    Cola grupo1 = new Cola();
    Cola grupo2 = new Cola();
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabMascota = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextNoVacunas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextCosto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbM = new javax.swing.JRadioButton();
        rbH = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jTextEdad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rb2 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        jButAñadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabMascotas = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabNoMascotas = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButEliminarUltClase = new javax.swing.JButton();
        jButEliMenosPrimClase = new javax.swing.JButton();
        jButEliMenosPenultClase = new javax.swing.JButton();
        jButEliminarUltFrame = new javax.swing.JButton();
        jButEliMenosPrimFrame = new javax.swing.JButton();
        jButEliMenosPenultFrame = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButVisualizarGpo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabMascota.setText("MASCOTAS");

        jLabel2.setText("Nombre");

        jLabel1.setText("Tipo:");

        jTextTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTipoActionPerformed(evt);
            }
        });

        jLabel3.setText("No. Vacunas");

        jTextNoVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNoVacunasActionPerformed(evt);
            }
        });

        jLabel4.setText("Costo Vac");

        jTextCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCostoActionPerformed(evt);
            }
        });

        jLabel5.setText("Sexo");

        buttonGroup1.add(rbM);
        rbM.setText("Macho");

        buttonGroup1.add(rbH);
        rbH.setText("Hembra");

        jLabel6.setText("Edad");

        jLabel7.setText("Grupo");

        buttonGroup2.add(rb2);
        rb2.setText("Grupo 2");

        buttonGroup2.add(rb1);
        rb1.setText("Grupo 1");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        jButAñadir.setText("Añadir");
        jButAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAñadirActionPerformed(evt);
            }
        });

        jTabMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTabMascotas);

        jLabel8.setText("Número de mascotas en cada grupo");

        jLabel9.setText("GRUPO");

        jTabNoMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Grupo 1", "Grupo 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTabNoMascotas);
        if (jTabNoMascotas.getColumnModel().getColumnCount() > 0) {
            jTabNoMascotas.getColumnModel().getColumn(0).setResizable(false);
            jTabNoMascotas.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel10.setText("COMPETENCIA 11");

        jButEliminarUltClase.setText("ELI ULT");
        jButEliminarUltClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliminarUltClaseActionPerformed(evt);
            }
        });

        jButEliMenosPrimClase.setText("ELI MENOS PRIM");
        jButEliMenosPrimClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliMenosPrimClaseActionPerformed(evt);
            }
        });

        jButEliMenosPenultClase.setText("ELI MENOS PENULT");
        jButEliMenosPenultClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliMenosPenultClaseActionPerformed(evt);
            }
        });

        jButEliminarUltFrame.setText("ELI ULT");
        jButEliminarUltFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliminarUltFrameActionPerformed(evt);
            }
        });

        jButEliMenosPrimFrame.setText("ELI MENOS PRIM");
        jButEliMenosPrimFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliMenosPrimFrameActionPerformed(evt);
            }
        });

        jButEliMenosPenultFrame.setText("ELI MENOS PENULT");
        jButEliMenosPenultFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliMenosPenultFrameActionPerformed(evt);
            }
        });

        jLabel11.setText("COMPETENCIA 12");

        jButVisualizarGpo.setText("Visualizar Gpo");
        jButVisualizarGpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVisualizarGpoActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(1, 1, 1)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbH)
                            .addComponent(rbM)
                            .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb2)
                            .addComponent(rb1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNoVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButAñadir))
                    .addComponent(jLabMascota)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21)
                        .addComponent(jTextCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButVisualizarGpo)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(43, 43, 43)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButEliMenosPrimClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButEliMenosPenultClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButEliMenosPenultFrame)
                    .addComponent(jLabel11)
                    .addComponent(jButEliminarUltClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButEliminarUltFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButEliMenosPrimFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabMascota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextNoVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbH, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButAñadir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel10)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButEliminarUltClase)
                                .addGap(18, 18, 18)
                                .addComponent(jButEliMenosPrimClase)
                                .addGap(18, 18, 18)
                                .addComponent(jButEliMenosPenultClase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButEliminarUltFrame)
                                .addGap(18, 18, 18)
                                .addComponent(jButEliMenosPrimFrame)
                                .addGap(18, 18, 18)
                                .addComponent(jButEliMenosPenultFrame))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jButVisualizarGpo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void actualizarNoMascotasGpos() {
        jTabNoMascotas.setValueAt(grupo1.Length(), 0, 0);
        jTabNoMascotas.setValueAt(grupo2.Length(), 0, 1);
    }
    private void jTextTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTipoActionPerformed

    private void jTextNoVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNoVacunasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNoVacunasActionPerformed

    private void jTextCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCostoActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void jButAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAñadirActionPerformed
        // TODO add your handling code here:
        Cola grupoSel = rb1.isSelected()? grupo1 : grupo2;
        if(jTextNombre.getText().isEmpty() || jTextTipo.getText().isEmpty() ||
           jTextNoVacunas.getText().isEmpty() || jTextCosto.getText().isEmpty()
           || jTextEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NO SE PUDO GUARDAR LA MASCOTA"
                    + " , DEBE LLENAR TODOS LOS CAMPOS",
                    "ERROR", JOptionPane.ERROR_MESSAGE); } 
        
        else if(! grupoSel.Full()) {        
            Mascota m = new Mascota(jTextNombre.getText(), jTextTipo.getText(), 
                                    Integer.parseInt(jTextNoVacunas.getText()),
                                    Double.parseDouble(jTextCosto.getText()), 
                                    rbM.isSelected()? "Macho" : "Hembra",   
                                    Integer.parseInt(jTextEdad.getText()));
        
            grupoSel.Insert(m);
            jTabNoMascotas.setValueAt(grupoSel.Length(), 0, rb1.isSelected()? 0 : 1);
        } else {
            JOptionPane.showMessageDialog(this, "YA ESTA LLENO EL GRUPO",
                                          "ERROR", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jButAñadirActionPerformed

    private void jButVisualizarGpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVisualizarGpoActionPerformed
        // TODO add your handling code here:
        Cola grupoSel = rb1.isSelected()? grupo1 : grupo2;
        Cola aux = new Cola(grupoSel.Length());
        DefaultTableModel modelo = (DefaultTableModel) jTabMascotas.getModel();
        modelo.setColumnCount(0);
        for(int i=grupoSel.Length();i > 0;i--)
            modelo.addColumn(i);
        int col = grupoSel.Length() - 1;
        while (!grupoSel.Empty()) {
            Mascota m = grupoSel.Remove();
            jTabMascotas.setValueAt(m.getNombre(),0,col);
            jTabMascotas.setValueAt(m.getTipo(),1,col);
            jTabMascotas.setValueAt(m.getNoVacunas(),2,col);
            jTabMascotas.setValueAt(m.getCostoVacunas(), 3, col);
            jTabMascotas.setValueAt(m.getSexo(), 4, col);
            jTabMascotas.setValueAt(m.getEdad(), 5, col--);
            aux.Insert(m);
        }
        while (!aux.Empty()) 
            grupoSel.Insert(aux.Remove());
    }//GEN-LAST:event_jButVisualizarGpoActionPerformed

    private void jButEliminarUltClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliminarUltClaseActionPerformed
        Cola grupoSel = rb1.isSelected()? grupo1 : grupo2;
        grupoSel.EliminarUltimo();
        actualizarNoMascotasGpos();
    }//GEN-LAST:event_jButEliminarUltClaseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTabNoMascotas.setValueAt(grupo1.Length(), 0, 0);
        jTabNoMascotas.setValueAt(grupo2.Length(), 0, 1);    
    }//GEN-LAST:event_formWindowOpened

    private void jButEliminarUltFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliminarUltFrameActionPerformed
        // TODO add your handling code here:
        Cola grupoSel = rb1.isSelected()? grupo1 : grupo2;
        if(!grupoSel.Empty()) {
            Cola aux = new Cola();
            while(grupoSel.Length() > 1)
                aux.Insert(grupoSel.Remove());
            grupoSel.Remove();
            while(!aux.Empty())
                grupoSel.Insert(aux.Remove());
             actualizarNoMascotasGpos();     
        }
    }//GEN-LAST:event_jButEliminarUltFrameActionPerformed

    private void jButEliMenosPrimClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliMenosPrimClaseActionPerformed
        // TODO add your handling code here:
        Cola grupoSel = rb1.isSelected()? grupo1 : grupo2;
        grupoSel.EliminarMenosPrimero();
        actualizarNoMascotasGpos();
    }//GEN-LAST:event_jButEliMenosPrimClaseActionPerformed

    private void jButEliMenosPenultClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliMenosPenultClaseActionPerformed
        // TODO add your handling code here
        Cola grupoSel = rb1.isSelected()? grupo1 : grupo2;
        grupoSel.EliminarMenosPenultimo();
        actualizarNoMascotasGpos();
    }//GEN-LAST:event_jButEliMenosPenultClaseActionPerformed

    private void jButEliMenosPrimFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliMenosPrimFrameActionPerformed
        // TODO add your handling code here:
        Cola grupoSel = rb1.isSelected()? grupo1 : grupo2;
        if(grupoSel.Length() > 1) {
            Cola aux = new Cola();
            aux.Insert(grupoSel.Remove());
            while(!grupoSel.Empty())
                grupoSel.Remove();
            grupoSel.Insert(aux.Remove());
            actualizarNoMascotasGpos();
        }
        
            
            
    }//GEN-LAST:event_jButEliMenosPrimFrameActionPerformed

    private void jButEliMenosPenultFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliMenosPenultFrameActionPerformed
        // TODO add your handling code here:
        Cola grupoSel = rb1.isSelected()? grupo1 : grupo2;
        if(!grupoSel.Empty()) {
            Cola aux = new Cola();
            while(grupoSel.Length() > 2)
                grupoSel.Remove();
            aux.Insert(grupoSel.Remove());
            grupoSel.Remove();
            grupoSel.Insert(aux.Remove());
            actualizarNoMascotasGpos();
        }
       
            
    }//GEN-LAST:event_jButEliMenosPenultFrameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cola grupoSel = rb1.isSelected()? grupo1 : grupo2;
        grupoSel.Examen();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButAñadir;
    private javax.swing.JButton jButEliMenosPenultClase;
    private javax.swing.JButton jButEliMenosPenultFrame;
    private javax.swing.JButton jButEliMenosPrimClase;
    private javax.swing.JButton jButEliMenosPrimFrame;
    private javax.swing.JButton jButEliminarUltClase;
    private javax.swing.JButton jButEliminarUltFrame;
    private javax.swing.JButton jButVisualizarGpo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabMascota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabMascotas;
    private javax.swing.JTable jTabNoMascotas;
    private javax.swing.JTextField jTextCosto;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextNoVacunas;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextTipo;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rbH;
    private javax.swing.JRadioButton rbM;
    // End of variables declaration//GEN-END:variables
}
