/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package AppGrafica;

import javax.swing.JOptionPane;

/**
 *
 * @author friosa
 */
public class RecursividadApp extends javax.swing.JFrame {
    /** Creates new form RecursividadApp */
    public RecursividadApp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFactorial = new javax.swing.JButton();
        txfN = new javax.swing.JTextField();
        btnSumaNat = new javax.swing.JButton();
        btnSumaNatRef = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txfX = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnExEJ17Ref = new javax.swing.JButton();
        btnDiv5 = new javax.swing.JButton();
        btnDiv5Ref = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALGORITMOS RECURSIVOS");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("n:");

        btnFactorial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFactorial.setText("FACTORIAL");
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });

        txfN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSumaNat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSumaNat.setText("SUMA N NAT");
        btnSumaNat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaNatActionPerformed(evt);
            }
        });

        btnSumaNatRef.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSumaNatRef.setText("SUMA N NAT -REF-");
        btnSumaNatRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaNatRefActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("x:");

        txfX.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("SUMA EXA EJ17");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnExEJ17Ref.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExEJ17Ref.setText("SUMA EXA EJ17 -REF-");
        btnExEJ17Ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExEJ17RefActionPerformed(evt);
            }
        });

        btnDiv5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDiv5.setText("DIV / 5");
        btnDiv5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiv5ActionPerformed(evt);
            }
        });

        btnDiv5Ref.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDiv5Ref.setText("DIV / 5 -REF-");
        btnDiv5Ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiv5RefActionPerformed(evt);
            }
        });

        jButton2.setText("EXAMEN1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfN, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfX))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDiv5Ref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDiv5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExEJ17Ref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSumaNatRef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFactorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSumaNat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFactorial))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumaNat)
                    .addComponent(jLabel2)
                    .addComponent(txfX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(btnSumaNatRef, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExEJ17Ref, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDiv5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiv5Ref, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        int n = Integer.parseInt(txfN.getText());
        if (n < 0)
            JOptionPane.showMessageDialog(this,"FACTORIAL DE UN NUMERO NEGATIVO NO ESTA DEFINIDO",
                    "ERROR ....",JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this,"FACTORIAL = "+Utilidades.Fact(n),
                    "FACTORIAL DE " + n,JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnFactorialActionPerformed

    private void btnSumaNatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaNatActionPerformed
        int n = Integer.parseInt(txfN.getText());
        if (n < 0)
            JOptionPane.showMessageDialog(this,"LA SUMA NO ESTA DEFINIDA",
                    "ERROR ....",JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this,"SUMA = "+Utilidades.Suma(n),
                    "SUMA DE LOS PRIMEROS " + n + " numeros naturales",
                    JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnSumaNatActionPerformed

    private void btnSumaNatRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaNatRefActionPerformed
        int n = Integer.parseInt(txfN.getText());
        int[] suma = {0};
        if (n < 0)
            JOptionPane.showMessageDialog(this,"LA SUMA NO ESTA DEFINIDA",
                    "ERROR ....",JOptionPane.PLAIN_MESSAGE);
        else {
            Utilidades.Suma(n,suma);
            JOptionPane.showMessageDialog(this,"SUMA = "+ suma[0],
                    "SUMA DE LOS PRIMEROS " + n + " numeros naturales",
                    JOptionPane.PLAIN_MESSAGE);
        } 
    }//GEN-LAST:event_btnSumaNatRefActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int nt = Integer.parseInt(txfN.getText());
        double x = Double.parseDouble(txfX.getText());
        if (x <= 0.0 || nt <= 0)
            JOptionPane.showMessageDialog(this,"LA SUMA NO ESTA DEFINIDA",
                    "ERROR ....",JOptionPane.PLAIN_MESSAGE);
        else
           JOptionPane.showMessageDialog(this,"SUMA EXA EJ17 = "+Utilidades.Suma(x,nt),
                    "SUMA x = " + x + " numeros de terminos = "+nt,
                    JOptionPane.PLAIN_MESSAGE); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExEJ17RefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExEJ17RefActionPerformed
        int nt = Integer.parseInt(txfN.getText());
        double x = Double.valueOf(txfX.getText());
        if (x <= 0.0 || nt <= 0)
            JOptionPane.showMessageDialog(this,"LA SUMA NO ESTA DEFINIDA",
                    "ERROR ....",JOptionPane.PLAIN_MESSAGE);
        else {
            double[] suma = {0.0};
            Utilidades.Suma(x,nt,suma);
           JOptionPane.showMessageDialog(this,"SUMA EXA EJ17 = "+suma[0],
                    "SUMA x = " + x + " numeros de terminos = "+nt,
                    JOptionPane.PLAIN_MESSAGE); 
        }
    }//GEN-LAST:event_btnExEJ17RefActionPerformed

    private void btnDiv5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiv5ActionPerformed
        int n1 = Integer.parseInt(txfN.getText());
        int n2 = Integer.parseInt(txfX.getText());
        if (Utilidades.NoDiv(n1,n2)>0)
            JOptionPane.showMessageDialog(this,"SUMA DIV / 5 = "+
                    (double)Utilidades.Suma(n1,n2)/Utilidades.NoDiv(n1,n2),
                    "PROMEDIO DE DIVISIBLES POR 5 "+n1+" , "+n2,
                    JOptionPane.PLAIN_MESSAGE); 
    }//GEN-LAST:event_btnDiv5ActionPerformed

    private void btnDiv5RefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiv5RefActionPerformed
        int n1 = Integer.parseInt(txfN.getText());
        int n2 = Integer.parseInt(txfX.getText());
    /*    int[] suma = {0};
        Utilidades.Suma(n1,n2,suma);
        JOptionPane.showMessageDialog(this,"SUMA DIV / 5 = "+suma[0],
                    "SUMA DE DIVISIBLES POR 5 "+n1+" , "+n2,
                    JOptionPane.PLAIN_MESSAGE); */
    }//GEN-LAST:event_btnDiv5RefActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(txfN.getText());
        double n2 = Double.parseDouble(txfX.getText());
        if(n2 > n1) {
            double nt = n2-n1-1;
            JOptionPane.showMessageDialog(this, (Utilidades.Sumando(n1, n2)/nt));
        }
        else
            JOptionPane.showMessageDialog(this, "Error");
            
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecursividadApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecursividadApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecursividadApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecursividadApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecursividadApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiv5;
    private javax.swing.JButton btnDiv5Ref;
    private javax.swing.JButton btnExEJ17Ref;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnSumaNat;
    private javax.swing.JButton btnSumaNatRef;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txfN;
    private javax.swing.JTextField txfX;
    // End of variables declaration//GEN-END:variables

}
