/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppGrafica;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author friosa
 */
public class AroblesAlumnosApp extends javax.swing.JFrame {
    private Arbol grupo1 = new Arbol();
    private Arbol grupo2 = new Arbol();
    /**
     * Creates new form AroblesAlumnosApp
     */
    public AroblesAlumnosApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLeerAlu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnLeerAlu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNoAlusGpo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVisuaGpo = new javax.swing.JTable();
        btnVisuaGpo = new javax.swing.JButton();
        btnPromedio = new javax.swing.JButton();
        btnPromedioRef = new javax.swing.JButton();
        btnNoOcurr = new javax.swing.JButton();
        btnGrupoBal = new javax.swing.JButton();
        btnNoAprob = new javax.swing.JButton();
        btnPromAprob = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAprob2 = new javax.swing.JButton();
        btnVisuaRep = new javax.swing.JButton();
        btnBalRef = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GRUPOS DE ALUMNOS -ARBOLES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb1.setSelected(true);
        rb1.setText("GRUPO 1");

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rb2.setText("GRUPO 2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb2))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb1)
                .addGap(18, 18, 18)
                .addComponent(rb2)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tblLeerAlu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblLeerAlu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "No.CTRL", "NOMBRE", "CALIFICACIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLeerAlu);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ALUMNO");

        btnLeerAlu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLeerAlu.setText("LEER");
        btnLeerAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerAluActionPerformed(evt);
            }
        });

        tblNoAlusGpo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "GRUPO 1", "GRUPO 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblNoAlusGpo);
        if (tblNoAlusGpo.getColumnModel().getColumnCount() > 0) {
            tblNoAlusGpo.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("No. ALUMNOS");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup2.add(rb3);
        rb3.setSelected(true);
        rb3.setText("PREORDEN");

        buttonGroup2.add(rb4);
        rb4.setText("INORDEN");

        buttonGroup2.add(rb5);
        rb5.setText("POSORDEN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb3)
                    .addComponent(rb4)
                    .addComponent(rb5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblVisuaGpo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "NO. CTRL", "NOMBRE", "CALIFICACIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblVisuaGpo);

        btnVisuaGpo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVisuaGpo.setText("VISUA GRUPO");
        btnVisuaGpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisuaGpoActionPerformed(evt);
            }
        });

        btnPromedio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPromedio.setText("PROMEDIO GRUPO");
        btnPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioActionPerformed(evt);
            }
        });

        btnPromedioRef.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPromedioRef.setText("PROMEDIO GRUPO -REF-");
        btnPromedioRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioRefActionPerformed(evt);
            }
        });

        btnNoOcurr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNoOcurr.setText("NO. OCURRENCIAS");
        btnNoOcurr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoOcurrActionPerformed(evt);
            }
        });

        btnGrupoBal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGrupoBal.setText("BALANCEADO?");
        btnGrupoBal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupoBalActionPerformed(evt);
            }
        });

        btnNoAprob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNoAprob.setText("APROBADOS");
        btnNoAprob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoAprobActionPerformed(evt);
            }
        });

        btnPromAprob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPromAprob.setText("PROM APROBADOS");
        btnPromAprob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromAprobActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAprob2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAprob2.setText("APROBADOS (2)");
        btnAprob2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprob2ActionPerformed(evt);
            }
        });

        btnVisuaRep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVisuaRep.setText("VISUA REPROB");
        btnVisuaRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisuaRepActionPerformed(evt);
            }
        });

        btnBalRef.setText("BAL(2)");
        btnBalRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalRefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVisuaGpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAprob2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVisuaRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLeerAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPromedioRef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNoOcurr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGrupoBal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNoAprob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPromAprob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBalRef)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLeerAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPromedio)
                            .addComponent(btnGrupoBal)
                            .addComponent(btnBalRef))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPromedioRef)
                            .addComponent(btnNoAprob))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNoOcurr)
                            .addComponent(btnPromAprob))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnVisuaGpo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAprob2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVisuaRep))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar(Arbol grupo) throws IllegalAccessException {
        if (Integer.parseInt(tblLeerAlu.getValueAt(0, 2).toString()) > 100)
            throw new IllegalAccessException("LA CALIFICACION NO PUEDE SER MAYOR QUE 100");
        grupo.Add(new TipoElem(tblLeerAlu.getValueAt(0, 0).toString(),
                        tblLeerAlu.getValueAt(0, 1).toString(),
                        Integer.parseInt(tblLeerAlu.getValueAt(0, 2).toString())));
    }
    private void btnLeerAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerAluActionPerformed
        Arbol grupoSel = rb1.isSelected()? grupo1 : grupo2;
        grupoSel.Add(new TipoElem(tblLeerAlu.getValueAt(0, 0).toString(),
                        tblLeerAlu.getValueAt(0, 1).toString(),
                        Integer.parseInt(tblLeerAlu.getValueAt(0, 2).toString())));
        tblNoAlusGpo.setValueAt(grupoSel.Length(),0,rb1.isSelected()? 0 : 1);
    }//GEN-LAST:event_btnLeerAluActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tblNoAlusGpo.setValueAt(grupo1.Length(), 0, 0);
        tblNoAlusGpo.setValueAt(grupo2.Length(), 0, 1);
    }//GEN-LAST:event_formWindowOpened

    private void Visua(TipoElem elem,DefaultTableModel modelo) {
        Object[] o = new Object[4]; 
        o[0] = modelo.getRowCount()+1;
        o[1] = elem.NoCon();
        o[2] = elem.Nombre();
        o[3] = elem.Calif();
        modelo.addRow(o);
    }
    private void Preorden(Nodo p,DefaultTableModel modelo) {
        if (p != null) {
            Visua(p.Info(),modelo);
            Preorden(p.Izq(),modelo);
            Preorden(p.Der(),modelo);
        }
    }
    private void Inorden(Nodo p,DefaultTableModel modelo) {
        if (p != null) {
            Inorden(p.Izq(),modelo);
            Visua(p.Info(),modelo);
            Inorden(p.Der(),modelo);
        }
    }
    private void Posorden(Nodo p,DefaultTableModel modelo) {
        if (p != null) {
            Posorden(p.Izq(),modelo);
            Posorden(p.Der(),modelo);
            Visua(p.Info(),modelo);
        }
    }
    private void btnVisuaGpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisuaGpoActionPerformed
        Arbol grupoSel = rb1.isSelected()? grupo1 : grupo2;
        DefaultTableModel modelo = (DefaultTableModel) tblVisuaGpo.getModel();
        modelo.setRowCount(0);
        if (rb3.isSelected())
            Preorden(grupoSel.Raiz(),modelo);
        else if (rb4.isSelected())
            Inorden(grupoSel.Raiz(),modelo);
        else
            Posorden(grupoSel.Raiz(),modelo);
    }//GEN-LAST:event_btnVisuaGpoActionPerformed

    private int Suma(Nodo p) {
        if (p == null)
            return 0;
        else
            return p.Info().Calif() + Suma(p.Izq()) + Suma(p.Der());
    }
    
    private void btnPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioActionPerformed
        Arbol grupoSel = rb1.isSelected()? grupo1 : grupo2;
        if (grupoSel.Empty())
            JOptionPane.showMessageDialog(this, "GRUPO VACIO", 
                    "ERROR ...", JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "PROMEDIO = " + 
                    (double) Suma(grupoSel.Raiz())/grupoSel.Length(), 
                    "PROMEDIO ...", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnPromedioActionPerformed

    private void Suma(Nodo p,int[] suma) {
        if (p != null) {
            suma[0] += p.Info().Calif();
            Suma(p.Izq(),suma);
            Suma(p.Der(),suma);
        }
    }
    
    private void btnPromedioRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioRefActionPerformed
        Arbol grupoSel = rb1.isSelected()? grupo1 : grupo2;
        if (grupoSel.Empty())
            JOptionPane.showMessageDialog(this, "GRUPO VACIO", 
                    "ERROR ...", JOptionPane.PLAIN_MESSAGE);
        else {
            int[] suma = {0};
            Suma(grupoSel.Raiz(),suma);
            JOptionPane.showMessageDialog(this, "PROMEDIO = " + 
                    (double) suma[0] / grupoSel.Length(), 
                    "PROMEDIO CON REFERENCIA...", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnPromedioRefActionPerformed

    private void btnNoOcurrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoOcurrActionPerformed
        Arbol grupoSel = rb1.isSelected()? grupo1 : grupo2;
        Nodo p = grupoSel.Raiz();
        int noOcurr = 0;
        int califBusq = Integer.parseInt(tblLeerAlu.getValueAt(0,2).toString());
        while (p!=null) {
            noOcurr += p.Info().Calif() == califBusq ? 1 : 0;
            p = califBusq >= p.Info().Calif() ? p.Der() : p.Izq();
        }
        JOptionPane.showMessageDialog(this, "NO. OCURRENCIAS = " + noOcurr, 
                    "CÁLCULO DEL NO. OCURRENCIAS ...", 
                    JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnNoOcurrActionPerformed

    private int NoNodos(Nodo p) {
        if (p == null)
            return 0;
        else
            return NoNodos(p.Izq()) + 1 + NoNodos(p.Der());
    }
    private void btnGrupoBalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoBalActionPerformed
        Arbol grupoSel = rb1.isSelected()? grupo1 : grupo2;
        if (grupoSel.Empty())
            JOptionPane.showMessageDialog(this, "GRUPO VACIO ", 
                    "ERROR ...", 
                    JOptionPane.PLAIN_MESSAGE);
        else {
            int noNodosIzq = NoNodos(grupoSel.Raiz().Izq());
            int noNodosDer = NoNodos(grupoSel.Raiz().Der());
            JOptionPane.showMessageDialog(this,
               (Math.abs(noNodosIzq-noNodosDer)<=1? "ESTA BALANCEADO":"NO ESTA BALANCEADO"), 
                    "RESULTADO ....", 
                    JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnGrupoBalActionPerformed

    private void NoAprob(Nodo p,int[] noAprob) {
        if (p!=null) {
            NoAprob(p.Izq(),noAprob);
            noAprob[0] += p.Info().Calif() >= 70? 1 : 0;    //inorden
            NoAprob(p.Der(),noAprob);       
        }
    }
    private void btnNoAprobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoAprobActionPerformed
        Arbol grupoSel = rb1.isSelected()? grupo1 : grupo2;
        int[] noAprob = {0};
        NoAprob(grupoSel.Raiz(),noAprob);
        JOptionPane.showMessageDialog(this, 
                "NO. APROBADOS = "+noAprob[0], 
                    "RESULTADO ...", 
                    JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnNoAprobActionPerformed

    private void SumaAprob(Nodo p,int[] sumaAprob) {
        if (p!=null) {
            SumaAprob(p.Izq(),sumaAprob);
            SumaAprob(p.Der(),sumaAprob);
            sumaAprob[0] += p.Info().Calif() >= 70? p.Info().Calif() : 0;
        }
    }
    private void btnPromAprobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromAprobActionPerformed
        Arbol grupoSel = rb1.isSelected()? grupo1 : grupo2;
        int[] noAprob = {0};
        NoAprob(grupoSel.Raiz(),noAprob);
        if (noAprob[0] == 0)
            JOptionPane.showMessageDialog(this, 
                "NO HAY APROBADOS, DADO QUE ESTÁN EN EL GRUPO DE UN SERVIDOR", 
                    "RESULTADO ...", 
                    JOptionPane.PLAIN_MESSAGE);
        else {
            int[] sumaAprob = {0};
            SumaAprob(grupoSel.Raiz(),sumaAprob);
            JOptionPane.showMessageDialog(this, 
                "PROMEDIO APROBADOS = "+(double)sumaAprob[0]/noAprob[0], 
                    "RESULTADO DEL PROMEDIO ...", 
                    JOptionPane.PLAIN_MESSAGE);
        } 
    }//GEN-LAST:event_btnPromAprobActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Arbol grupoSel = rb1.isSelected()? grupo1 : grupo2;
        TipoElem elemBuscar = new TipoElem(tblLeerAlu.getValueAt(0, 0).toString(),
                        tblLeerAlu.getValueAt(0, 1).toString(),
                        Integer.parseInt(tblLeerAlu.getValueAt(0, 2).toString()));
        Nodo p = grupoSel.Buscar(elemBuscar);
        if (p==null)
             JOptionPane.showMessageDialog(this,"NO SE ENCONTRO AL ALUMNO",
                     "BUSQUEDA ...",JOptionPane.PLAIN_MESSAGE);
          else
             JOptionPane.showMessageDialog(this,"DATOS DEL ALUMNO:\n"+
                     p.Info().NoCon()+"\n"+p.Info().Nombre()+"\n"+
                     p.Info().Calif(),
                     "BUSQUEDA ...",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private int noAprob(Nodo p) {
        if (p!= null)
            return noAprob(p.Izq()) + (p.Info().Calif()>=70?1:0) + noAprob(p.Der());
        else
            return 0;
    }
    
    private void btnAprob2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprob2ActionPerformed
         Arbol grupoSel = rb1.isSelected()? grupo1 : grupo2;
         JOptionPane.showMessageDialog(this, 
                "NO. APROBADOS = "+noAprob(grupoSel.Raiz()), 
                    "RESULTADO ...", 
                    JOptionPane.PLAIN_MESSAGE);                                         
    }//GEN-LAST:event_btnAprob2ActionPerformed

    private void Visua(TipoElem elem) {
        DefaultTableModel modelo = (DefaultTableModel) tblVisuaGpo.getModel();
        Object[] o = new Object[4];
        o[0] = modelo.getRowCount()+1;
        o[1] = elem.NoCon();
        o[2] = elem.Nombre();
        o[3] = elem.Calif();
        modelo.addRow(o);
    }
    private void VisuaRep(Nodo p) {
        if (p != null) {
            if(p.Info().Calif() < 70) 
                Visua(p.Info());
            VisuaRep(p.Izq());
            VisuaRep(p.Der());
        }
    }
    private void btnVisuaRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisuaRepActionPerformed
        Arbol grupoSel = rb1.isSelected()? grupo1 : grupo2;
        DefaultTableModel modelo = (DefaultTableModel) tblVisuaGpo.getModel();
        modelo.setRowCount(0);
        VisuaRep(grupoSel.Raiz());
    }//GEN-LAST:event_btnVisuaRepActionPerformed

    private void NoNodos(Nodo p, int[] noNodos) {
        if(p == null)
            return;
        else {
            NoNodos(p.Izq(), noNodos);  
            NoNodos(p.Der(), noNodos);
            noNodos[0]++;
        }
            
    }
    
    private void btnBalRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalRefActionPerformed
        // TODO add your handling code here:
        Arbol grupoSel = rb1.isSelected()? grupo1 : grupo2;
        if (grupoSel.Empty())
            JOptionPane.showMessageDialog(this, "GRUPO VACIO ", 
                    "ERROR ...", 
                    JOptionPane.PLAIN_MESSAGE);
        else {
            int[] noNodosIzq = {0};
            NoNodos(grupoSel.Raiz().Izq(), noNodosIzq);
            int[] noNodosDer = {0};
            NoNodos(grupoSel.Raiz().Der(), noNodosDer);
            JOptionPane.showMessageDialog(this,
               (Math.abs(noNodosIzq[0]-noNodosDer[0])<=1? "ESTA BALANCEADO":"NO ESTA BALANCEADO"), 
                    "RESULTADO ....", 
                    JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnBalRefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AroblesAlumnosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AroblesAlumnosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AroblesAlumnosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AroblesAlumnosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AroblesAlumnosApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprob2;
    private javax.swing.JButton btnBalRef;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGrupoBal;
    private javax.swing.JButton btnLeerAlu;
    private javax.swing.JButton btnNoAprob;
    private javax.swing.JButton btnNoOcurr;
    private javax.swing.JButton btnPromAprob;
    private javax.swing.JButton btnPromedio;
    private javax.swing.JButton btnPromedioRef;
    private javax.swing.JButton btnVisuaGpo;
    private javax.swing.JButton btnVisuaRep;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JTable tblLeerAlu;
    private javax.swing.JTable tblNoAlusGpo;
    private javax.swing.JTable tblVisuaGpo;
    // End of variables declaration//GEN-END:variables
}
