/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica_03;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AM
 */
public class JFrame extends javax.swing.JFrame {
    Pila grupo1 = new Pila();
    Pila grupo2 = new Pila();
    DefaultTableModel modelo;

    public JFrame() {
        initComponents();
        modelo = (DefaultTableModel)jTabMascotas.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabAnadirMascota = new javax.swing.JLabel();
        jLabNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextCosto = new javax.swing.JTextField();
        jLabCosto = new javax.swing.JLabel();
        jLabSexo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabNoMasc = new javax.swing.JTable();
        jButtAnadir = new javax.swing.JButton();
        jLabEdad = new javax.swing.JLabel();
        jLabTipo = new javax.swing.JLabel();
        jLabNoVacunas = new javax.swing.JLabel();
        jTextTipo = new javax.swing.JTextField();
        jRadioM = new javax.swing.JRadioButton();
        jRadioH = new javax.swing.JRadioButton();
        jLabGrupo = new javax.swing.JLabel();
        jComboGrupo = new javax.swing.JComboBox<>();
        jTextEdad = new javax.swing.JTextField();
        jTextNoVacunas = new javax.swing.JTextField();
        jLabNoMasc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabMascotas = new javax.swing.JTable();
        jLabGrupoVis = new javax.swing.JLabel();
        jButtVisGpo = new javax.swing.JButton();
        jButtIntercambiar1 = new javax.swing.JButton();
        jButtEliminar2 = new javax.swing.JButton();
        jButtIntercambiar3 = new javax.swing.JButton();
        jLabInt1aUlt = new javax.swing.JLabel();
        jLabElimMay100 = new javax.swing.JLabel();
        jLabIntUlt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabAnadirMascota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabAnadirMascota.setText("AÑADIR MASCOTA");

        jLabNombre.setText("Nombre");

        jLabCosto.setText("Costo");

        jLabSexo.setText("Sexo");

        jTabNoMasc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Grupo 1", "Grupo 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabNoMasc);
        if (jTabNoMasc.getColumnModel().getColumnCount() > 0) {
            jTabNoMasc.getColumnModel().getColumn(0).setResizable(false);
            jTabNoMasc.getColumnModel().getColumn(1).setResizable(false);
        }

        jButtAnadir.setText("Añadir");
        jButtAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtAnadirActionPerformed(evt);
            }
        });

        jLabEdad.setText("Edad");

        jLabTipo.setText("Tipo");

        jLabNoVacunas.setText("# Vacunas");

        jTextTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTipoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioM);
        jRadioM.setSelected(true);
        jRadioM.setText("Macho");

        buttonGroup1.add(jRadioH);
        jRadioH.setText("Hembra");

        jLabGrupo.setText("Grupo");

        jComboGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grupo 1", "Grupo 2" }));

        jLabNoMasc.setText("NO. MASCOTAS EN CADA GRUPO:");

        jTabMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "No. de Vacunas", "Costp", "Sexo", "Edad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTabMascotas);
        if (jTabMascotas.getColumnModel().getColumnCount() > 0) {
            jTabMascotas.getColumnModel().getColumn(0).setResizable(false);
            jTabMascotas.getColumnModel().getColumn(1).setResizable(false);
            jTabMascotas.getColumnModel().getColumn(2).setResizable(false);
            jTabMascotas.getColumnModel().getColumn(3).setResizable(false);
            jTabMascotas.getColumnModel().getColumn(4).setResizable(false);
            jTabMascotas.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabGrupoVis.setText("Grupo");

        jButtVisGpo.setText("Visualizar Grupo");
        jButtVisGpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtVisGpoActionPerformed(evt);
            }
        });

        jButtIntercambiar1.setText("Intercambiar");
        jButtIntercambiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtIntercambiar1ActionPerformed(evt);
            }
        });

        jButtEliminar2.setText("Eliminar");
        jButtEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtEliminar2ActionPerformed(evt);
            }
        });

        jButtIntercambiar3.setText("Intercambiar");
        jButtIntercambiar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtIntercambiar3ActionPerformed(evt);
            }
        });

        jLabInt1aUlt.setText("Masc. de ambos grupos menos los topes");

        jLabElimMay100.setText("Los Osos de ambos grupos");

        jLabIntUlt.setText("Masc. de ambos grupos menos los topes");

        jLabel1.setText("usando un método en la clase Pila");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabNoMasc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabSexo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jRadioM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioH))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabAnadirMascota)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabNombre)
                                        .addComponent(jLabTipo))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextNombre)
                                        .addComponent(jTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabCosto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabNoVacunas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextNoVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabGrupo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabEdad)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jComboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabGrupoVis)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtVisGpo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtEliminar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtIntercambiar3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabInt1aUlt)
                            .addComponent(jLabElimMay100)
                            .addComponent(jLabIntUlt)
                            .addComponent(jButtIntercambiar1)
                            .addComponent(jLabel1))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabGrupoVis)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jButtVisGpo)
                                .addGap(55, 55, 55)
                                .addComponent(jLabInt1aUlt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14)
                                .addComponent(jButtIntercambiar1)
                                .addGap(45, 45, 45)
                                .addComponent(jLabElimMay100)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtEliminar2)
                                .addGap(11, 11, 11)
                                .addComponent(jLabIntUlt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtIntercambiar3))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabAnadirMascota)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabNombre)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabTipo)
                            .addComponent(jTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabNoVacunas)
                            .addComponent(jTextNoVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabCosto)
                            .addComponent(jTextCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabSexo)
                            .addComponent(jRadioM)
                            .addComponent(jRadioH))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabEdad)
                            .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabGrupo)
                            .addComponent(jComboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabNoMasc)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Pila getGrupoSel() {
        int noGrupoSel = jComboGrupo.getSelectedIndex();
        switch(noGrupoSel){
            case 0:
                return grupo1;
            case 1:
                return grupo2;
            default:
                return grupo1;
        }
    }
    
    private void actualizarNoMascotasGpos() {
        jTabNoMasc.setValueAt(grupo1.Length(), 0, 0);
        jTabNoMasc.setValueAt(grupo2.Length(), 0, 1);
    }
    
    private void eliminarOsos(Pila p) {
        Pila aux = new Pila();
        for(int i = p.Length(); i > 0; i--) {
            Mascota m = p.Pop();
            if(m.getTipo().equals("oso") || m.getTipo().equals("OSO")
               || m.getTipo().equals("Oso")) {
                
            }
            else {
                aux.Push(m);
            }
        }
        while(!aux.Empty()) {
            p.Push(aux.Pop());
        }
    }
    
    private void jButtAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtAnadirActionPerformed
        Pila grupoSel = getGrupoSel();
        if(jTextNombre.getText().isEmpty() || jTextTipo.getText().isEmpty() ||
           jTextNoVacunas.getText().isEmpty() || jTextCosto.getText().isEmpty()
           || jTextEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NO SE PUDO GUARDAR LA MASCOTA"
                    + " , DEBE LLENAR TODOS LOS CAMPOS",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if(! grupoSel.Full()) {
                
            Mascota m = new Mascota(jTextNombre.getText(), jTextTipo.getText(), 
                                    Integer.parseInt(jTextNoVacunas.getText()),
                                    Double.parseDouble(jTextCosto.getText()), 
                                    jRadioM.isSelected() ? "M" : "F",   
                                    Integer.parseInt(jTextEdad.getText()));
        
            grupoSel.Push(m);
            jTabNoMasc.setValueAt(grupoSel.Length(), 0, jComboGrupo.getSelectedIndex());
        } else {
            JOptionPane.showMessageDialog(this, "YA ESTA LLENO EL GRUPO",
                    "ERROR", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jButtAnadirActionPerformed

    private void jTextTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTipoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTabNoMasc.setValueAt(grupo1.Length(), 0, 0);
        jTabNoMasc.setValueAt(grupo2.Length(), 0, 1);
    }//GEN-LAST:event_formWindowOpened

    private void jButtVisGpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtVisGpoActionPerformed
        // TODO add your handling code here:
        Pila grupoSel = getGrupoSel();
        Pila aux = new Pila(grupoSel.Length());
        jLabGrupoVis.setText("Grupo " + Integer.toString(jComboGrupo.getSelectedIndex() + 1));
        while (modelo.getRowCount() > 0)
            modelo.removeRow(0);
     
        while(! grupoSel.Empty()) {
            Mascota m = grupoSel.Pop();
            aux.Push(m);
            Object[] o = new Object[6];
            o[0] = m.getNombre();
            o[1] = m.getTipo();
            o[2] = m.getNoVacunas();
            o[3] = m.getCostoVacunas();
            o[4] = m.getSexo();
            o[5] = m.getEdad();
            modelo.addRow(o);
        }
        
        while(! aux.Empty()) 
            grupoSel.Push(aux.Pop());                         
    }//GEN-LAST:event_jButtVisGpoActionPerformed

    private void jButtIntercambiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtIntercambiar1ActionPerformed
        if(grupo1.Length() > 1 && grupo2.Length() > 1) {
            grupo1.IntercambiarMenosTope(grupo2);
            actualizarNoMascotasGpos();  
        }
    }//GEN-LAST:event_jButtIntercambiar1ActionPerformed

    private void jButtIntercambiar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtIntercambiar3ActionPerformed
        // TODO add your handling code here:
        Mascota tope1 = grupo1.Pop();
        Mascota tope2 = grupo2.Pop();
        
        int tamGpo2 = grupo2.Length();
        while(!grupo1.Empty())
            grupo2.Push(grupo1.Pop());
        
        grupo2.Invertir();
        
        for(int j = tamGpo2; j>0; j--)
            grupo1.Push(grupo2.Pop());
        
        grupo1.Push(tope1);
        grupo2.Push(tope2);
        actualizarNoMascotasGpos();
    }//GEN-LAST:event_jButtIntercambiar3ActionPerformed

    private void jButtEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtEliminar2ActionPerformed
        if(grupo1.Length() > 0 && grupo2.Length() > 0) {
            eliminarOsos(grupo1);
            eliminarOsos(grupo2);
            actualizarNoMascotasGpos();
            jButtVisGpoActionPerformed(evt);
        }
    }//GEN-LAST:event_jButtEliminar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtAnadir;
    private javax.swing.JButton jButtEliminar2;
    private javax.swing.JButton jButtIntercambiar1;
    private javax.swing.JButton jButtIntercambiar3;
    private javax.swing.JButton jButtVisGpo;
    private javax.swing.JComboBox<String> jComboGrupo;
    private javax.swing.JLabel jLabAnadirMascota;
    private javax.swing.JLabel jLabCosto;
    private javax.swing.JLabel jLabEdad;
    private javax.swing.JLabel jLabElimMay100;
    private javax.swing.JLabel jLabGrupo;
    private javax.swing.JLabel jLabGrupoVis;
    private javax.swing.JLabel jLabInt1aUlt;
    private javax.swing.JLabel jLabIntUlt;
    private javax.swing.JLabel jLabNoMasc;
    private javax.swing.JLabel jLabNoVacunas;
    private javax.swing.JLabel jLabNombre;
    private javax.swing.JLabel jLabSexo;
    private javax.swing.JLabel jLabTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioH;
    private javax.swing.JRadioButton jRadioM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabMascotas;
    private javax.swing.JTable jTabNoMasc;
    private javax.swing.JTextField jTextCosto;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextNoVacunas;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextTipo;
    // End of variables declaration//GEN-END:variables
}
