/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppGrafica;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author friosa
 */
public class ArregloEnfoqueEstaticoAlumnosApp extends javax.swing.JFrame {
    final int MAXALUS = 35;
    private Alumno[] grupo1 = new Alumno[MAXALUS];
    private Alumno[] grupo2 = new Alumno[MAXALUS];
    private Alumno[] grupo3 = new Alumno[MAXALUS];
    private Alumno[] grupo4 = new Alumno[MAXALUS];
    private Alumno[] grupo5 = new Alumno[MAXALUS];
    private int[] noAlusGpo = {0,0,0,0,0};
    /**
     * Creates new form ArregloEnfoqueDinamicoAlumnosApp
     */
    public ArregloEnfoqueEstaticoAlumnosApp() {
        initComponents();
        for(int i=0;i<MAXALUS;i++) {
            grupo1[i] = new Alumno();
            grupo2[i] = new Alumno();
            grupo3[i] = new Alumno();
            grupo4[i] = new Alumno();
            grupo5[i] = new Alumno();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfNoCon = new javax.swing.JTextField();
        txfNombre = new javax.swing.JTextField();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        btnLeerAlumno = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbCalif = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbGrupo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNoAlusGpo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblNoGpoVisua = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVisuaGrupo = new javax.swing.JTable();
        btnVisuaGrupo = new javax.swing.JButton();
        btnVisuaDamas = new javax.swing.JButton();
        btnEjB = new javax.swing.JButton();
        btnInterAlusG4_G5Ref = new javax.swing.JButton();
        btnInterAlusG4_G5Copias = new javax.swing.JButton();
        btnEliReprobados = new javax.swing.JButton();
        btnEliPrimerAlu = new javax.swing.JButton();
        btnEliUltimoAlu = new javax.swing.JButton();
        btnReacomodo = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("LECTURA DE ALUMNO");

        jLabel2.setText("No. DE CONTROL:");

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("SEXO:");

        buttonGroup1.add(rb1);
        rb1.setSelected(true);
        rb1.setText("Masculino");

        buttonGroup1.add(rb2);
        rb2.setText("Femenino");

        btnLeerAlumno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLeerAlumno.setText("LEER ALUMNO");
        btnLeerAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerAlumnoActionPerformed(evt);
            }
        });

        jLabel8.setText("CALIFICACIÓN:");

        cbCalif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfNoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rb1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb2))
                                    .addComponent(cbCalif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(btnLeerAlumno)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txfNoCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rb1)
                            .addComponent(rb2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbCalif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLeerAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("SELECCIONA EL GRUPO:");

        cbGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRUPO 1", "GRUPO 2", "GRUPO 3", "GRUPO 4", "GRUPO 5" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("NO. DE ALUMNOS EN LOS GRUPOS:");

        tblNoAlusGpo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblNoAlusGpo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "GRUPO 1", "GRUPO 2", "GRUPO 3", "GRUPO 4", "GRUPO 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNoAlusGpo);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNoGpoVisua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNoGpoVisua.setText("GRUPO");

        tblVisuaGrupo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblVisuaGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "NO. CONTROL", "NOMBRE", "SEXO", "CALIFICACIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVisuaGrupo.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblVisuaGrupo);

        btnVisuaGrupo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVisuaGrupo.setLabel("VISUA GRUPO");
        btnVisuaGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisuaGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVisuaGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNoGpoVisua))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNoGpoVisua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisuaGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );

        btnVisuaDamas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVisuaDamas.setText("VISUA DAMAS");
        btnVisuaDamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisuaDamasActionPerformed(evt);
            }
        });

        btnEjB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEjB.setText("COMPARA ALUMNAS G1 vs G3");
        btnEjB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjBActionPerformed(evt);
            }
        });

        btnInterAlusG4_G5Ref.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInterAlusG4_G5Ref.setText("INTER ALUS G4 Y G5 -REF-");
        btnInterAlusG4_G5Ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterAlusG4_G5RefActionPerformed(evt);
            }
        });

        btnInterAlusG4_G5Copias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInterAlusG4_G5Copias.setText("INTER ALUS G4 Y G5 -COPIAS-");
        btnInterAlusG4_G5Copias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterAlusG4_G5CopiasActionPerformed(evt);
            }
        });

        btnEliReprobados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliReprobados.setText("ELIMINAR REPROBADOS");
        btnEliReprobados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliReprobadosActionPerformed(evt);
            }
        });

        btnEliPrimerAlu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliPrimerAlu.setText("ELI PRIMER ALUMNO");
        btnEliPrimerAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliPrimerAluActionPerformed(evt);
            }
        });

        btnEliUltimoAlu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEliUltimoAlu.setText("ELI ÚLTIMO ALUMNO");
        btnEliUltimoAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliUltimoAluActionPerformed(evt);
            }
        });

        btnReacomodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReacomodo.setText("REACOMODO");
        btnReacomodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReacomodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEjB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVisuaDamas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInterAlusG4_G5Ref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInterAlusG4_G5Copias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliReprobados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliPrimerAlu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliUltimoAlu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReacomodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6))
                                .addGap(139, 139, 139))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVisuaDamas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEjB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInterAlusG4_G5Ref, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInterAlusG4_G5Copias, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliReprobados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliPrimerAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliUltimoAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReacomodo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cbCalif.removeAllItems();
        for(int i=0;i<=100;i++)
            cbCalif.addItem(Integer.toString(i));
        tblNoAlusGpo.setValueAt(noAlusGpo[0],0,0);
        tblNoAlusGpo.setValueAt(noAlusGpo[1],0,1);
        tblNoAlusGpo.setValueAt(noAlusGpo[2],0,2);
        tblNoAlusGpo.setValueAt(noAlusGpo[3],0,3);
        tblNoAlusGpo.setValueAt(noAlusGpo[4],0,4);  
    }//GEN-LAST:event_formWindowOpened
    private Alumno[] getGrupoSel() {
        int noGrupoSel = cbGrupo.getSelectedIndex();
        switch (noGrupoSel) {
            case 0: 
                return grupo1;
            case 1: 
                return grupo2;
            case 2: 
                return grupo3;
            case 3: 
                return grupo4;
            case 4: 
                return grupo5;
            default:
                return grupo1;
        }  
    } 

    private void btnLeerAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerAlumnoActionPerformed
        Alumno[] grupoSel = getGrupoSel();
        int noGrupoSel = cbGrupo.getSelectedIndex();
        if (noAlusGpo[noGrupoSel] < MAXALUS) {
            grupoSel[noAlusGpo[noGrupoSel]++].Leer(txfNoCon.getText(),
                                                    txfNombre.getText(),
                                                rb1.isSelected()?'M':'F',
                                Integer.parseInt(cbCalif.getSelectedItem().toString()));
            tblNoAlusGpo.setValueAt(noAlusGpo[noGrupoSel], 0, noGrupoSel);
        }
        else
          JOptionPane.showMessageDialog(this,
                "ERROR ... YA NO HAY CUPO EN EL GRUPO SELECCIONADO", 
                "GRUPO LLENO",JOptionPane.PLAIN_MESSAGE);  
    }//GEN-LAST:event_btnLeerAlumnoActionPerformed

    private void btnVisuaGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisuaGrupoActionPerformed
        Alumno[] grupoSel = getGrupoSel();
        lblNoGpoVisua.setText("GRUPO "+
                              Integer.toString(cbGrupo.getSelectedIndex()+1));
        DefaultTableModel modelo=(DefaultTableModel) tblVisuaGrupo.getModel();
        while (tblVisuaGrupo.getRowCount() > 0)
            modelo.removeRow(0);
        int noGrupoSel = cbGrupo.getSelectedIndex();
        for(int i=0;i<noAlusGpo[noGrupoSel];i++) {
            Object[] o = new Object[5];
            o[0] = i+1;
            o[1] = grupoSel[i].getNoCon();
            o[2] = grupoSel[i].getNombre();
            o[3] = grupoSel[i].getSexo();
            o[4] = grupoSel[i].getCalif();
            modelo.addRow(o);
        }  
    }//GEN-LAST:event_btnVisuaGrupoActionPerformed

    private void btnVisuaDamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisuaDamasActionPerformed
        Alumno[] grupoSel = getGrupoSel();
        int noDamas = 0;
        int noGrupoSel = cbGrupo.getSelectedIndex();
        for(int i=0;i<noAlusGpo[noGrupoSel];i++)
            if(grupoSel[i].getSexo()=='F')
                noDamas++;
        JOptionPane.showMessageDialog(this,
                "NÚMERO DE ALUMNAS = "+Integer.toString(noDamas), 
                "Alumnas en el grupo seleccionado ...",JOptionPane.PLAIN_MESSAGE); 
    }//GEN-LAST:event_btnVisuaDamasActionPerformed
    private int getNoDamasEnGrupo(Alumno[] grupo) {
        int noDamas = 0;
        int noGrupoSel = cbGrupo.getSelectedIndex();
        for(int i=0;i < noAlusGpo[noGrupoSel];i++)
            if(grupo[i].getSexo()=='F')
                noDamas++; 
        return noDamas;  
    }  
    private void btnEjBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjBActionPerformed
        int noDamas1 = getNoDamasEnGrupo(grupo1);
        int noDamas3 = getNoDamasEnGrupo(grupo3);
        if(noDamas1 > noDamas3)
            JOptionPane.showMessageDialog(this,
                    "EL GRUPO1 TIENE MAS ALUMNAS QUE EL GRUPO 3 -> "+
                    Integer.toString(noDamas1)+" vs "+Integer.toString(noDamas3),
                    "Ejercicio (b) ...", JOptionPane.PLAIN_MESSAGE);
        else if(noDamas3 > noDamas1)
            JOptionPane.showMessageDialog(this,
                    "EL GRUPO3 TIENE MAS ALUMNAS QUE EL GRUPO 1 -> "+
                    Integer.toString(noDamas3)+" vs "+Integer.toString(noDamas1),
                    "Ejercicio (b) ...", JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this,
                    "EL GRUPO1 Y EL GRUPO 3 TIENEN EL MISMO NO. DE ALUMNAS-> "+
                    Integer.toString(noDamas1)+" vs "+Integer.toString(noDamas3),
                    "Ejercicio (b) ...", JOptionPane.PLAIN_MESSAGE); 
    }//GEN-LAST:event_btnEjBActionPerformed

    private void btnInterAlusG4_G5RefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterAlusG4_G5RefActionPerformed
        Alumno[] aux = grupo4;
        grupo4 = grupo5;
        grupo5 = aux;
        tblNoAlusGpo.setValueAt(noAlusGpo[3], 0, 3);
        tblNoAlusGpo.setValueAt(noAlusGpo[4], 0, 4);
        JOptionPane.showMessageDialog(this, 
                "EL INTERCAMBIO DE ALUMNOS ENTER LOS GRUPOS 4 Y 5 SE HA REALIZADO",
                "Ejercicio (c)", JOptionPane.PLAIN_MESSAGE); 
    }//GEN-LAST:event_btnInterAlusG4_G5RefActionPerformed

    private void btnInterAlusG4_G5CopiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterAlusG4_G5CopiasActionPerformed
        Alumno[] aux = new Alumno[noAlusGpo[3]];
        for(int i=0;i < noAlusGpo[3];i++)
            aux[i] = new Alumno();
        for(int i=0;i < noAlusGpo[3];i++)
            aux[i].Copia(grupo4[i]);
        for(int i=0;i < noAlusGpo[4];i++)
            grupo4[i].Copia(grupo5[i]);
        noAlusGpo[3] = noAlusGpo[4];
        for(int i=0;i < aux.length;i++)
            grupo5[i].Copia(aux[i]);
        noAlusGpo[4] = aux.length;
        tblNoAlusGpo.setValueAt(noAlusGpo[3], 0, 3);
        tblNoAlusGpo.setValueAt(noAlusGpo[4], 0, 4);
        JOptionPane.showMessageDialog(this, 
                "EL INTERCAMBIO DE ALUMNOS ENTER LOS GRUPOS 4 Y 5 SE HA REALIZADO",
                "Ejercicio (d)", JOptionPane.PLAIN_MESSAGE); 
    }//GEN-LAST:event_btnInterAlusG4_G5CopiasActionPerformed
    private void eliReprobados(Alumno[] grupo,int col) {
        if (noAlusGpo[col] > 0) {
            Alumno[] aux = new Alumno[noAlusGpo[col]];
            for(int i=0;i<noAlusGpo[col];i++)
                aux[i] = new Alumno();
            int noAprob = 0;
            for(int i=0;i<noAlusGpo[col];i++) 
                if (grupo[i].getCalif() >= 70)
                    aux[noAprob++].Copia(grupo[i]);
            for(int i=0;i < noAprob;i++) 
                grupo[i].Copia(aux[i]);
            noAlusGpo[col] = noAprob;
            tblNoAlusGpo.setValueAt(noAlusGpo[col],0,col);
        }
    }
    private void btnEliReprobadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliReprobadosActionPerformed
        eliReprobados(grupo1,0);
        eliReprobados(grupo2,1);
        eliReprobados(grupo3,2);
        eliReprobados(grupo4,3);
        eliReprobados(grupo5,4);
        JOptionPane.showMessageDialog(this, 
                "SE HAN ELIMINADO LOS ALUMNOS REPROBADOS EN LOS 5 GRUPOS",
                "Ejercicio (e)", JOptionPane.PLAIN_MESSAGE); 
    }//GEN-LAST:event_btnEliReprobadosActionPerformed

    private void btnEliPrimerAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliPrimerAluActionPerformed
        Alumno[] grupoSel = getGrupoSel();
        int noGrupoSel = cbGrupo.getSelectedIndex();
        if (noAlusGpo[noGrupoSel] > 0) {
            /*    Alumno[] aux = new Alumno[noAlusGpo[noGrupoSel]];
            for(int i=0;i < noAlusGpo[noGrupoSel];i++) {
                aux[i] = new Alumno();
                aux[i].Copia(grupoSel[i]);
            }
            for(int i=1;i < aux.length;i++)
               grupoSel[i-1].Copia(aux[i]); */
            for(int i=1;i < noAlusGpo[noGrupoSel];i++)
               grupoSel[i-1].Copia(grupoSel[i]); 
            noAlusGpo[noGrupoSel]--;
            tblNoAlusGpo.setValueAt(noAlusGpo[noGrupoSel], 0, noGrupoSel);
            JOptionPane.showMessageDialog(this, 
                    "SE HA ELIMINADO EL PRIMER ALUMNO EN EL GRUPO SELECCIONADO",
                    "Ejercicio (f)", JOptionPane.PLAIN_MESSAGE); 
        }
    }//GEN-LAST:event_btnEliPrimerAluActionPerformed
    private void eliUltimoAlumno(int col) {
        if (noAlusGpo[col] > 0)
            noAlusGpo[col]--;
        tblNoAlusGpo.setValueAt(noAlusGpo[col], 0, col);
    } 
    private void btnEliUltimoAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliUltimoAluActionPerformed
        eliUltimoAlumno(0);
        eliUltimoAlumno(1);
        eliUltimoAlumno(2);
        eliUltimoAlumno(3);
        eliUltimoAlumno(4);
        JOptionPane.showMessageDialog(this, 
                "SE HA ELIMINADO EL ÚLTIMO ALUMNO EN LOS 5 GRUPOS",
                "Ejercicio (g)", JOptionPane.PLAIN_MESSAGE); 
    }//GEN-LAST:event_btnEliUltimoAluActionPerformed

    private void btnReacomodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReacomodoActionPerformed
        Alumno[] grupoSel = getGrupoSel();
        int noGrupoSel = cbGrupo.getSelectedIndex(); 
        if(noAlusGpo[noGrupoSel] > 1) {
            Alumno[] mujeres = new Alumno[noAlusGpo[noGrupoSel]];
            Alumno[] hombres = new Alumno[noAlusGpo[noGrupoSel]];
            for(int i=0;i < noAlusGpo[noGrupoSel];i++) {
                mujeres[i] = new Alumno();
                hombres[i] = new Alumno();
            }
            int noMujeres = 0, noHombres = 0;
            for(int i=0;i < noAlusGpo[noGrupoSel];i++)
                if (grupoSel[i].getSexo() == 'F')
                    mujeres[noMujeres++].Copia(grupoSel[i]);
                else
                    hombres[noHombres++].Copia(grupoSel[i]);
            int indiceGrupoSel = 0;
            for(int i=0;i < noMujeres;i++)
                grupoSel[indiceGrupoSel++].Copia(mujeres[i]);
            for(int i=0;i < noHombres;i++)
                grupoSel[indiceGrupoSel++].Copia(hombres[i]);
        }
        JOptionPane.showMessageDialog(this, 
                "SE HA REALIZADO EL REACOMODO ...",
                "Ejercicio (H)", JOptionPane.PLAIN_MESSAGE); 
    }//GEN-LAST:event_btnReacomodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArregloEnfoqueEstaticoAlumnosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArregloEnfoqueEstaticoAlumnosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArregloEnfoqueEstaticoAlumnosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArregloEnfoqueEstaticoAlumnosApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArregloEnfoqueEstaticoAlumnosApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjB;
    private javax.swing.JButton btnEliPrimerAlu;
    private javax.swing.JButton btnEliReprobados;
    private javax.swing.JButton btnEliUltimoAlu;
    private javax.swing.JButton btnInterAlusG4_G5Copias;
    private javax.swing.JButton btnInterAlusG4_G5Ref;
    private javax.swing.JButton btnLeerAlumno;
    private javax.swing.JButton btnReacomodo;
    private javax.swing.JButton btnVisuaDamas;
    private javax.swing.JButton btnVisuaGrupo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCalif;
    private javax.swing.JComboBox<String> cbGrupo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNoGpoVisua;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTable tblNoAlusGpo;
    private javax.swing.JTable tblVisuaGrupo;
    private javax.swing.JTextField txfNoCon;
    private javax.swing.JTextField txfNombre;
    // End of variables declaration//GEN-END:variables
}
