/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica_01;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AM
 */
public class JFrame extends javax.swing.JFrame {
    private ArrayList<Mascota> grupo1 = new ArrayList<>();
    private ArrayList<Mascota> grupo2 = new ArrayList<>();
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabAnadirMascota = new javax.swing.JLabel();
        jLabNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextCosto = new javax.swing.JTextField();
        jLabCosto = new javax.swing.JLabel();
        jLabSexo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabNoMasc = new javax.swing.JTable();
        jButtAnadir = new javax.swing.JButton();
        jLabEdad = new javax.swing.JLabel();
        jLabTipo = new javax.swing.JLabel();
        jLabNoVacunas = new javax.swing.JLabel();
        jTextTipo = new javax.swing.JTextField();
        jRadioM = new javax.swing.JRadioButton();
        jRadioH = new javax.swing.JRadioButton();
        jLabGrupo = new javax.swing.JLabel();
        jComboGrupo = new javax.swing.JComboBox<>();
        jTextEdad = new javax.swing.JTextField();
        jTextNoVacunas = new javax.swing.JTextField();
        jLabNoMasc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabMascotas = new javax.swing.JTable();
        jLabGrupoVis = new javax.swing.JLabel();
        jButtVisGpo = new javax.swing.JButton();
        jButtIntercambiar1 = new javax.swing.JButton();
        jButtEliminar2 = new javax.swing.JButton();
        jButtIntercambiar3 = new javax.swing.JButton();
        jLabInt1aUlt = new javax.swing.JLabel();
        jLabElimMay100 = new javax.swing.JLabel();
        jLabIntUlt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabAnadirMascota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabAnadirMascota.setText("AÑADIR MASCOTA");

        jLabNombre.setText("Nombre");

        jLabCosto.setText("Costo");

        jLabSexo.setText("Sexo");

        jTabNoMasc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Grupo 1", "Grupo 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabNoMasc);
        if (jTabNoMasc.getColumnModel().getColumnCount() > 0) {
            jTabNoMasc.getColumnModel().getColumn(0).setResizable(false);
            jTabNoMasc.getColumnModel().getColumn(1).setResizable(false);
        }

        jButtAnadir.setText("Añadir");
        jButtAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtAnadirActionPerformed(evt);
            }
        });

        jLabEdad.setText("Edad");

        jLabTipo.setText("Tipo");

        jLabNoVacunas.setText("# Vacunas");

        jTextTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTipoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioM);
        jRadioM.setSelected(true);
        jRadioM.setText("Macho");

        buttonGroup1.add(jRadioH);
        jRadioH.setText("Hembra");

        jLabGrupo.setText("Grupo");

        jComboGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grupo 1", "Grupo 2" }));

        jLabNoMasc.setText("NO. MASCOTAS EN CADA GRUPO:");

        jTabMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Nombre", "Tipo", "# Vac", "$ Vac", "Sexo", "Edad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTabMascotas);
        if (jTabMascotas.getColumnModel().getColumnCount() > 0) {
            jTabMascotas.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTabMascotas.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTabMascotas.getColumnModel().getColumn(2).setResizable(false);
            jTabMascotas.getColumnModel().getColumn(3).setResizable(false);
            jTabMascotas.getColumnModel().getColumn(4).setResizable(false);
            jTabMascotas.getColumnModel().getColumn(5).setResizable(false);
            jTabMascotas.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabGrupoVis.setText("Grupo");

        jButtVisGpo.setText("Visualizar Grupo");
        jButtVisGpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtVisGpoActionPerformed(evt);
            }
        });

        jButtIntercambiar1.setText("Intercambiar");
        jButtIntercambiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtIntercambiar1ActionPerformed(evt);
            }
        });

        jButtEliminar2.setText("Eliminar");
        jButtEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtEliminar2ActionPerformed(evt);
            }
        });

        jButtIntercambiar3.setText("Intercambiar");
        jButtIntercambiar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtIntercambiar3ActionPerformed(evt);
            }
        });

        jLabInt1aUlt.setText("1a mascota --> última / mismo grupo");

        jLabElimMay100.setText("Costo Vacunas > 100 / ambos grupos");

        jLabIntUlt.setText("últ. masc <--> últ. masc. / ambos grupos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabNoMasc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabSexo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jRadioM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioH))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabAnadirMascota)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabNombre)
                                        .addComponent(jLabTipo))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextNombre)
                                        .addComponent(jTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabCosto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabNoVacunas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextNoVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabGrupo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabEdad)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jComboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabGrupoVis)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtVisGpo)
                            .addComponent(jButtIntercambiar1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtEliminar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtIntercambiar3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabInt1aUlt)
                            .addComponent(jLabElimMay100)
                            .addComponent(jLabIntUlt))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabGrupoVis)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jButtVisGpo)
                                .addGap(41, 41, 41)
                                .addComponent(jLabInt1aUlt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtIntercambiar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabElimMay100)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtEliminar2)
                                .addGap(11, 11, 11)
                                .addComponent(jLabIntUlt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtIntercambiar3))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabAnadirMascota)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabNombre)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabTipo)
                            .addComponent(jTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabNoVacunas)
                            .addComponent(jTextNoVacunas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabCosto)
                            .addComponent(jTextCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabSexo)
                            .addComponent(jRadioM)
                            .addComponent(jRadioH))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabEdad)
                            .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabGrupo)
                            .addComponent(jComboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabNoMasc)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<Mascota> getGrupoSel() {
        int noGrupoSel = jComboGrupo.getSelectedIndex();
        switch(noGrupoSel){
            case 0:
                return grupo1;
            case 1:
                return grupo2;
            default:
                return grupo1;
        }
    }
    
    private void eliminarPorCosto(ArrayList<Mascota> grupo){
        for (int i = 0; i < grupo.size(); i++){
            if(grupo.get(i).getCostoVacunas() > 100){
                grupo.remove(i);
            }
        }
    }
    
    private void jButtAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtAnadirActionPerformed
        // TODO add your handling code here:
        ArrayList<Mascota> grupoSel = getGrupoSel();
        Mascota masc = new Mascota();
        masc.Leer(jTextNombre.getText(), jTextTipo.getText(), 
                  Integer.parseInt(jTextNoVacunas.getText()),
                  Double.parseDouble(jTextCosto.getText()), jRadioM.isSelected() ? 'M' : 'F',   
                  Integer.parseInt(jTextEdad.getText()));
        grupoSel.add(masc);
        jTabNoMasc.setValueAt(grupoSel.size(), 0, jComboGrupo.getSelectedIndex());
    }//GEN-LAST:event_jButtAnadirActionPerformed

    private void jTextTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTipoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jTabNoMasc.setValueAt(grupo1.size(), 0, 0);
        jTabNoMasc.setValueAt(grupo1.size(), 0, 1);
    }//GEN-LAST:event_formWindowOpened

    private void jButtVisGpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtVisGpoActionPerformed
        // TODO add your handling code here:
        ArrayList<Mascota> grupoSel = getGrupoSel();
        jLabGrupoVis.setText("Grupo " + Integer.toString(jComboGrupo.getSelectedIndex() + 1));
        DefaultTableModel modelo = (DefaultTableModel) jTabMascotas.getModel();
        modelo.setRowCount(0);
        int i = 0;
        for(Mascota masc : grupoSel){
            Object[] o = new Object[7];
            o[0] = ++i;
            o[1] = masc.getNombre();
            o[2] = masc.getTipo();
            o[3] = masc.getNoVacunas();
            o[4] = masc.getCostoVacunas();
            o[5] = masc.getSexo();
            o[6] = masc.getEdad();
            modelo.addRow(o);
        }
    }//GEN-LAST:event_jButtVisGpoActionPerformed

    private void jButtIntercambiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtIntercambiar1ActionPerformed
        // TODO add your handling code here:
        ArrayList<Mascota> grupoSel = getGrupoSel();
        Mascota aux = grupoSel.get(0);
        grupoSel.set(0, grupoSel.get(grupoSel.size() - 1));
        grupoSel.set(grupoSel.size() - 1, aux);
    }//GEN-LAST:event_jButtIntercambiar1ActionPerformed

    private void jButtIntercambiar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtIntercambiar3ActionPerformed
        // TODO add your handling code here:
        Mascota aux = grupo1.get(grupo1.size() - 1);
        grupo1.set(grupo1.size() - 1, grupo2.get(grupo2.size() - 1));
        grupo2.set(grupo2.size() - 1, aux);
    }//GEN-LAST:event_jButtIntercambiar3ActionPerformed

    private void jButtEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtEliminar2ActionPerformed
        // TODO add your handling code here:
        eliminarPorCosto(grupo1);
        eliminarPorCosto(grupo2);
    }//GEN-LAST:event_jButtEliminar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtAnadir;
    private javax.swing.JButton jButtEliminar2;
    private javax.swing.JButton jButtIntercambiar1;
    private javax.swing.JButton jButtIntercambiar3;
    private javax.swing.JButton jButtVisGpo;
    private javax.swing.JComboBox<String> jComboGrupo;
    private javax.swing.JLabel jLabAnadirMascota;
    private javax.swing.JLabel jLabCosto;
    private javax.swing.JLabel jLabEdad;
    private javax.swing.JLabel jLabElimMay100;
    private javax.swing.JLabel jLabGrupo;
    private javax.swing.JLabel jLabGrupoVis;
    private javax.swing.JLabel jLabInt1aUlt;
    private javax.swing.JLabel jLabIntUlt;
    private javax.swing.JLabel jLabNoMasc;
    private javax.swing.JLabel jLabNoVacunas;
    private javax.swing.JLabel jLabNombre;
    private javax.swing.JLabel jLabSexo;
    private javax.swing.JLabel jLabTipo;
    private javax.swing.JRadioButton jRadioH;
    private javax.swing.JRadioButton jRadioM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabMascotas;
    private javax.swing.JTable jTabNoMasc;
    private javax.swing.JTextField jTextCosto;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextNoVacunas;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextTipo;
    // End of variables declaration//GEN-END:variables
}
